In [3]:
import numpy as np

In [5]:
a=np.random.randint(1,10, size = (5,3))
a

array([[2, 4, 5],
       [8, 3, 9],
       [7, 3, 5],
       [8, 2, 7],
       [2, 8, 1]], dtype=int32)

In [6]:
np.max(a, axis=0)

array([8, 8, 9], dtype=int32)

In [7]:
np.max(a, axis=1)

array([5, 9, 7, 8, 8], dtype=int32)