In [36]:
import numpy as np

In [37]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [38]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [40]:
np.array([2,3,4],dtype=float)
np.array([1,2,3],dtype=float )

array([1., 2., 3.])

In [41]:
np.arange(1,99,2)
np.arange(1,10,2).reshape(5,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [42]:
np.arange(1,11).reshape(5,2)


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [43]:
np.random.randint(1,5,size=(2,2,2))
np.random.randint(1,10,size=(2,2,2))

array([[[3, 4],
        [5, 3]],

       [[3, 6],
        [2, 9]]], dtype=int32)

In [44]:
np.linspace(-10,10,10,dtype=int)
np.linspace(-20,20,10,dtype=float)

array([-20.        , -15.55555556, -11.11111111,  -6.66666667,
        -2.22222222,   2.22222222,   6.66666667,  11.11111111,
        15.55555556,  20.        ])

In [45]:
np.eye(2,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [46]:
a1=np.random.randint(1,11,size=(2,5,2),dtype=np.int64)
print(a1)

[[[10  9]
  [ 5  7]
  [ 5  9]
  [ 5  8]
  [ 3  2]]

 [[10  4]
  [ 1  7]
  [ 1 10]
  [ 9  8]
  [ 9  7]]]


In [47]:

a1=a1.astype(np.int32)
print(a1.dtype)

int32


In [48]:
la=np.arange(1,10,2,dtype=float)
print(la)
la=la.astype(np.int64)
print(la.dtype)


[1. 3. 5. 7. 9.]
int64


In [49]:
a2=np.arange(1,11).reshape(2,5)
a3=np.arange(11,21).reshape(2,5)

In [50]:
#scalar operations 
print(a2+2)
print(a2>2)

[[ 3  4  5  6  7]
 [ 8  9 10 11 12]]
[[False False  True  True  True]
 [ True  True  True  True  True]]


In [93]:
#vector operations 
a2*a3
a2>a3
print(a2)
np.max(a2,axis=1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([ 5, 10])

In [52]:
#mathematical functions 
np.max(a2,axis=0) #axis=0 is for column 
np.sum(a2)
np.prod(a2)
np.min(a2,axis=1)

array([1, 6])

In [53]:
np.mean(a3,axis=0)
np.std(a3,axis=1)

array([1.41421356, 1.41421356])

In [54]:
#trignometry 
np.sin(a2)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111]])

In [55]:
#dot product 
print(a2*a3)

[[ 11  24  39  56  75]
 [ 96 119 144 171 200]]


In [56]:
print(f"{a2}\n\n{a3}")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[11 12 13 14 15]
 [16 17 18 19 20]]


In [57]:
#for exponential function 
np.exp(a2)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04]])

In [58]:
np.random.randint(1,100,size=(10,10),dtype=np.int64)

array([[20, 70, 57, 28, 58, 60, 77, 13,  5, 24],
       [26, 19, 57, 96, 72, 51, 94, 18, 44, 45],
       [24, 25, 89,  3, 12, 16, 13, 14, 97, 51],
       [30, 88, 51, 27,  9, 22, 80, 30, 89, 38],
       [57, 76, 48,  5, 29, 20, 40, 20, 87, 27],
       [29, 56, 82, 83, 71, 65, 63, 49, 69,  2],
       [ 6, 54, 22, 65, 83, 52, 54, 44, 92, 29],
       [ 1, 41, 72, 53, 13, 85,  4,  4, 17, 43],
       [44, 42,  5, 12, 20,  3, 18, 46, 22, 29],
       [ 8, 34, 49, 84, 84, 57, 23,  9, 36, 31]])

In [59]:

a=np.round(np.arange(1,10,dtype=float))
print(a)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [60]:
np.round(np.random.random((2,3)))

array([[0., 1., 0.],
       [0., 1., 1.]])

In [61]:
np.floor(np.random.random((2,2)))

array([[0., 0.],
       [0., 0.]])

In [62]:
# round -> goes to nearest whole number and preferes even more 
#floor-> always goes or falls down 
#ceil-> always goes or rise up 

In [63]:
# 0->column 
#1-> row  

In [64]:
a=np.arange(10)
aa=np.random.randint(1,11,size=(2,5))
aaa=np.arange(8).reshape(2,2,2)

In [65]:
print(a[9:1:-1]) #same as list 

[9 8 7 6 5 4 3 2]


In [66]:
aa


array([[ 6,  8,  7,  2,  4],
       [10,  1,  6,  5,  9]], dtype=int32)

In [94]:
print(aa[1][0:3])
print(aa[0][1:3])

[10  1  6]
[8 7]


In [68]:
aaa


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [102]:
print(aaa[0][0][0:2])

[0 1]


In [70]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [71]:
a2[1,:] #gets column(num,:)

array([ 6,  7,  8,  9, 10])

In [72]:
a2[:,4]

array([ 5, 10])

In [73]:
ap=np.random.randint(1,13,size=(3,4))
ap

array([[ 7, 11, 10,  2],
       [ 4, 11,  7,  2],
       [ 5,  3, 12,  5]], dtype=int32)

In [74]:
ap[1:,0:2]

array([[ 4, 11],
       [ 5,  3]], dtype=int32)

In [105]:
ap[1,1:3]

array([11,  7], dtype=int32)

In [75]:
ap[::2,1::2]

array([[11,  2],
       [ 3,  5]], dtype=int32)

In [76]:
ap[1,1:]

array([11,  7,  2], dtype=int32)

In [77]:
aaa=np.arange(27).reshape(3,3,3)
aaa


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [109]:
aaa[::2,0::3,0::2]

array([[[ 0,  2]],

       [[18, 20]]])

In [79]:
for i in a:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [80]:
for i in aa:
    print(i)

[6 8 7 2 4]
[10  1  6  5  9]


In [81]:
for i in aaa:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [82]:
for i in np.nditer(aaa):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [83]:
#reshaping 
aa

array([[ 6,  8,  7,  2,  4],
       [10,  1,  6,  5,  9]], dtype=int32)

In [84]:
np.transpose(aa)
aa.T

array([[ 6, 10],
       [ 8,  1],
       [ 7,  6],
       [ 2,  5],
       [ 4,  9]], dtype=int32)

In [85]:
aa.ravel() 
#converts into 1D array f

array([ 6,  8,  7,  2,  4, 10,  1,  6,  5,  9], dtype=int32)

In [86]:
#stacking and splitting 

In [111]:
ak=np.arange(12).reshape(3,4)
al=np.arange(12).reshape(3,4)
print(ak)
print(al)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [88]:
ola=np.hstack((ak,al))
ola

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [112]:
haha=np.vstack((ak,al))
np.shape(ola)
haha

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
np.hsplit(ola,4)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]]),
 array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [91]:
np.vsplit(haha,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])]

In [ ]:
aaa.dtype
aaa.astype(np.int32)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]], dtype=int32)

: 