In [1]:
import numpy as np

In [2]:
# sort 
# return a copy of sorted copy of array 
a=np.random.randint(1,100,15)
a

array([ 2, 31, 53, 32, 75, 70, 41, 76, 12, 99, 54, 77,  1, 85, 66],
      dtype=int32)

In [3]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[94, 29, 71, 37],
       [97, 47, 39, 22],
       [80, 84, 10, 34],
       [24, 98, 22, 90],
       [ 6, 10, 74, 44],
       [53,  3, 53, 94]], dtype=int32)

In [4]:
np.sort(a)
np.sort(b,axis=0)

array([[ 6,  3, 10, 22],
       [24, 10, 22, 34],
       [53, 29, 39, 37],
       [80, 47, 53, 44],
       [94, 84, 71, 90],
       [97, 98, 74, 94]], dtype=int32)

In [5]:
#decending order 
np.sort(a)[::-1]

array([99, 85, 77, 76, 75, 70, 66, 54, 53, 41, 32, 31, 12,  2,  1],
      dtype=int32)

In [6]:
# np.append()
# adds the item into last 
np.append(a,100)

array([  2,  31,  53,  32,  75,  70,  41,  76,  12,  99,  54,  77,   1,
        85,  66, 100])

In [7]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[94., 29., 71., 37.,  1.],
       [97., 47., 39., 22.,  1.],
       [80., 84., 10., 34.,  1.],
       [24., 98., 22., 90.,  1.],
       [ 6., 10., 74., 44.,  1.],
       [53.,  3., 53., 94.,  1.]])

In [8]:
b.shape[0]

6

In [9]:
#concatinate ->add 
c=np.arange(6).reshape(2,3)
d=np.arange(6).reshape(2,3)

In [10]:
np.concatenate((c,d),axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [11]:
#np.unique gives unique items
np.unique(c)


array([0, 1, 2, 3, 4, 5])

In [12]:
#np.expand_dems()
a

array([ 2, 31, 53, 32, 75, 70, 41, 76, 12, 99, 54, 77,  1, 85, 66],
      dtype=int32)

In [13]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [14]:
#condition np.where(condition) -> returns the index of right 
np.where(a>50)

(array([ 2,  4,  5,  7,  9, 10, 11, 13, 14]),)

In [15]:
a[np.where(a%2==0)]=0
a

array([ 0, 31, 53,  0, 75,  0, 41,  0,  0, 99,  0, 77,  1, 85,  0],
      dtype=int32)

In [16]:
# np.argmax() -> returns the index of maximum value 
np.argmax(a)

np.int64(9)

In [17]:
np.argmin(a)

np.int64(0)

In [18]:
# for 2d array give axis also 
a

array([ 0, 31, 53,  0, 75,  0, 41,  0,  0, 99,  0, 77,  1, 85,  0],
      dtype=int32)

In [19]:
#np.cumsum()
#1,2,3,4 -> 1+2=3,3+3=6,6+4+10
np.cumsum(a)

array([  0,  31,  84,  84, 159, 159, 200, 200, 200, 299, 299, 376, 377,
       462, 462])

In [20]:
b

array([[94, 29, 71, 37],
       [97, 47, 39, 22],
       [80, 84, 10, 34],
       [24, 98, 22, 90],
       [ 6, 10, 74, 44],
       [53,  3, 53, 94]], dtype=int32)

In [21]:
np.cumsum(b,axis=0)
b

array([[94, 29, 71, 37],
       [97, 47, 39, 22],
       [80, 84, 10, 34],
       [24, 98, 22, 90],
       [ 6, 10, 74, 44],
       [53,  3, 53, 94]], dtype=int32)

In [22]:
#np.cumpro()
np.cumprod(a)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
#np.percentile() 
np.percentile(a,58)
#0 -> lowest 
#58-> median 

np.float64(32.19999999999999)

In [24]:
# np.histogram()
np.histogram(a,bins=[0,50,100])

(array([10,  5]), array([  0,  50, 100]))

In [26]:
#np.corrcoef
salary=np.array([20000,40000,25000,35000,60000])
experience=np.array([1,3,2,4,2])

In [27]:
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [28]:
#np.isin -> search multiple items 
a

array([ 0, 31, 53,  0, 75,  0, 41,  0,  0, 99,  0, 77,  1, 85,  0],
      dtype=int32)

In [29]:
np.isin(a,0)

array([ True, False, False,  True, False,  True, False,  True,  True,
       False,  True, False, False, False,  True])

In [32]:
#np.flip() 
# reverse 
a

array([ 0, 31, 53,  0, 75,  0, 41,  0,  0, 99,  0, 77,  1, 85,  0],
      dtype=int32)

In [31]:
np.flip(a)

array([ 0, 85,  1, 77,  0, 99,  0,  0, 41,  0, 75,  0, 53, 31,  0],
      dtype=int32)

In [33]:
b

array([[94, 29, 71, 37],
       [97, 47, 39, 22],
       [80, 84, 10, 34],
       [24, 98, 22, 90],
       [ 6, 10, 74, 44],
       [53,  3, 53, 94]], dtype=int32)

In [36]:
np.flip(b,axis=0)

array([[53,  3, 53, 94],
       [ 6, 10, 74, 44],
       [24, 98, 22, 90],
       [80, 84, 10, 34],
       [97, 47, 39, 22],
       [94, 29, 71, 37]], dtype=int32)

In [40]:
#np.put -exchange 
a
#makes permanent change 

array([10, 20, 53,  0, 75,  0, 41,  0,  0, 99,  0, 77,  1, 85,  0],
      dtype=int32)

In [41]:
np.put(a,[0,1],[10,20])

In [42]:
a

array([10, 20, 53,  0, 75,  0, 41,  0,  0, 99,  0, 77,  1, 85,  0],
      dtype=int32)

In [44]:
#np.delete()
np.delete(a,0)

array([20, 53,  0, 75,  0, 41,  0,  0, 99,  0, 77,  1, 85,  0],
      dtype=int32)

In [46]:
np.delete(a,np.where(a>50))

array([10, 20,  0,  0, 41,  0,  0,  0,  1,  0], dtype=int32)

In [48]:
m=np.array([1,2,3,4])
n=np.array([3,4,5,6])


In [49]:
np.union1d(n,m)

array([1, 2, 3, 4, 5, 6])

In [50]:
#np.intersection1d()

In [51]:
#np.setdiff1d()


In [52]:
#np.setxor() ->removes common part and gives the remaining part 

In [53]:
#np.in1d(array,value) ->gives bool 

In [54]:
#np.clip()
np.clip(a,a_min=25,a_max=75)

array([25, 25, 53, 25, 75, 25, 41, 25, 25, 75, 25, 75, 25, 75, 25],
      dtype=int32)