In [2]:
import numpy as np 
a=np.arange(10,50)
a=a[::-1]
print(a)
b=np.zeros((5,5))
b[::4,::4]+=1
b=b.astype(dtype=np.int8)
print(b)
c=np.array([1,2,0,0,4,0])
print(np.nonzero(c))
aa=np.arange(27).reshape(3,3,3)
print(aa.max())
print(aa.min())

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[[1 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 1]]
(array([0, 1, 4]),)
26
0


In [4]:
ar=np.arange(100).reshape(10,10)
ar

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [5]:
ar[2:,2:]

array([[22, 23, 24, 25, 26, 27, 28, 29],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47, 48, 49],
       [52, 53, 54, 55, 56, 57, 58, 59],
       [62, 63, 64, 65, 66, 67, 68, 69],
       [72, 73, 74, 75, 76, 77, 78, 79],
       [82, 83, 84, 85, 86, 87, 88, 89],
       [92, 93, 94, 95, 96, 97, 98, 99]])

In [6]:
ar[:,::-1]

array([[ 9,  8,  7,  6,  5,  4,  3,  2,  1,  0],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10],
       [29, 28, 27, 26, 25, 24, 23, 22, 21, 20],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [49, 48, 47, 46, 45, 44, 43, 42, 41, 40],
       [59, 58, 57, 56, 55, 54, 53, 52, 51, 50],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70],
       [89, 88, 87, 86, 85, 84, 83, 82, 81, 80],
       [99, 98, 97, 96, 95, 94, 93, 92, 91, 90]])

In [8]:
arr=np.arange(25).reshape(5,5)
arr[arr>12]

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [11]:
arr[~(arr%2==0)]=-1
arr


array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1],
       [10, -1, 12, -1, 14],
       [-1, 16, -1, 18, -1],
       [20, -1, 22, -1, 24]])

In [12]:
mat=np.arange(15).reshape(5,3)
vec=np.arange(3)
mat-vec

array([[ 0,  0,  0],
       [ 3,  3,  3],
       [ 6,  6,  6],
       [ 9,  9,  9],
       [12, 12, 12]])

In [ ]:
np.mean(ar,axis=0)/np.std(ar,axis=0)

array([1.5666989 , 1.60151443, 1.63632997, 1.6711455 , 1.70596103,
       1.74077656, 1.77559209, 1.81040762, 1.84522315, 1.88003868])

: 