# ARRAY METHOD

NumPy Array Properties and Methods
NumPy arrays have several useful properties and methods that can be used to manipulate them.

shape: Property that returns the dimensions of the array

ndim: Property that returns number of array dimensions

dtype: Property that returns data-type of the array’s elements

T: Transpose of the array’s elements

reshape(): Method to change the dimensions of an array. The product of old dimensions should match the product of new dimensions

ravel(): Method that collapses all values into a single axis or dimension and returns view of original array

flatten(): Method that collapses all values into a single axis or dimension and returns an independent copy of original array

sum(): Method that returns the sum of all elements in an array

cumsum(): Method that returns cumulative sum over given axis

prod(): Method that compute product over given axis

max(): Method that returns the maximum along a given axis

argmax(): Method that returns indeces of the maximum values along a given axis

clip(): Clip values beyond range to threshold values

np.concatenate(): Method to concatenate two or more arrays

np.split(): Method to split an array into multiple sub-arrays

np.vstack(): Method to stack arrays vertically

np.hstack(): Method to stack arrays horizontally

In [2]:
import numpy as np

In [3]:
a=np.random.randint(1,100,size=(2,3,3))

In [4]:
a

array([[[65,  8, 54],
        [73, 78, 40],
        [23, 20, 82]],

       [[97, 80, 57],
        [45, 71, 10],
        [49, 94, 54]]], dtype=int32)

In [5]:
a.T

array([[[65, 97],
        [73, 45],
        [23, 49]],

       [[ 8, 80],
        [78, 71],
        [20, 94]],

       [[54, 57],
        [40, 10],
        [82, 54]]], dtype=int32)

In [6]:
a.reshape(6,3)

array([[65,  8, 54],
       [73, 78, 40],
       [23, 20, 82],
       [97, 80, 57],
       [45, 71, 10],
       [49, 94, 54]], dtype=int32)

In [7]:
a.reshape(-1,3) # value thaxaina bhani -1 use garnne 

array([[65,  8, 54],
       [73, 78, 40],
       [23, 20, 82],
       [97, 80, 57],
       [45, 71, 10],
       [49, 94, 54]], dtype=int32)

In [8]:
#a.flatten() auta  banaidinxa
b=a.flatten()
b

array([65,  8, 54, 73, 78, 40, 23, 20, 82, 97, 80, 57, 45, 71, 10, 49, 94,
       54], dtype=int32)

In [9]:
a.sum()
a

array([[[65,  8, 54],
        [73, 78, 40],
        [23, 20, 82]],

       [[97, 80, 57],
        [45, 71, 10],
        [49, 94, 54]]], dtype=int32)

In [10]:
a.sum(axis=0) #0 baneko column ani 1 baneko row

array([[162,  88, 111],
       [118, 149,  50],
       [ 72, 114, 136]])

In [11]:
aa=np.random.randint(1,10,size=(2,2,2))
aa

array([[[6, 5],
        [7, 2]],

       [[6, 8],
        [3, 1]]], dtype=int32)

In [12]:
aa.sum(axis=0)

array([[12, 13],
       [10,  3]])

In [13]:
aa.sum(axis=1)

array([[13,  7],
       [ 9,  9]])

In [14]:
aa.max()

np.int32(8)

In [15]:
aa

array([[[6, 5],
        [7, 2]],

       [[6, 8],
        [3, 1]]], dtype=int32)

In [16]:
aa.cumsum(axis=0)

array([[[ 6,  5],
        [ 7,  2]],

       [[12, 13],
        [10,  3]]])

In [17]:
aa.trace() #diagonal sum

array([9, 6])

In [18]:
e=np.random.randint(1,10,size=(5,5))

In [19]:
e

array([[8, 4, 5, 9, 9],
       [5, 5, 7, 4, 8],
       [8, 6, 1, 7, 2],
       [2, 3, 1, 8, 2],
       [1, 5, 7, 1, 2]], dtype=int32)

In [20]:
e.sum(axis = 0) #column  wise

array([24, 23, 21, 29, 23])

In [21]:
e.sum(axis=1) #row wise 

array([35, 29, 24, 16, 16])

In [22]:
e.cumsum(axis=1)

array([[ 8, 12, 17, 26, 35],
       [ 5, 10, 17, 21, 29],
       [ 8, 14, 15, 22, 24],
       [ 2,  5,  6, 14, 16],
       [ 1,  6, 13, 14, 16]])

In [23]:
np.cumsum(e,axis=0)

array([[ 8,  4,  5,  9,  9],
       [13,  9, 12, 13, 17],
       [21, 15, 13, 20, 19],
       [23, 18, 14, 28, 21],
       [24, 23, 21, 29, 23]])

In [24]:
e.prod(axis=1)

array([12960,  5600,   672,    96,    70])

In [25]:
np.argmax(e,axis=1)

array([3, 4, 0, 3, 2])

In [26]:
e

array([[8, 4, 5, 9, 9],
       [5, 5, 7, 4, 8],
       [8, 6, 1, 7, 2],
       [2, 3, 1, 8, 2],
       [1, 5, 7, 1, 2]], dtype=int32)

In [27]:
e.max(axis=1)

array([9, 8, 8, 8, 7], dtype=int32)

In [28]:
e.min(axis=1)

array([4, 4, 1, 1, 1], dtype=int32)

In [29]:
e.clip(5,9) #yesle chai xuttauxa 5 to 9 ko bichma 

array([[8, 5, 5, 9, 9],
       [5, 5, 7, 5, 8],
       [8, 6, 5, 7, 5],
       [5, 5, 5, 8, 5],
       [5, 5, 7, 5, 5]], dtype=int32)

In [30]:
arr1=np.random.randint(1,10,size=(3,2))
arr2=np.random.randint(1,10,size=(3,2))


In [31]:
l=np.concatenate([arr1,arr2],axis=1)

In [32]:
l

array([[6, 1, 5, 5],
       [2, 5, 5, 4],
       [3, 6, 9, 2]], dtype=int32)

In [33]:
arr1

array([[6, 1],
       [2, 5],
       [3, 6]], dtype=int32)

In [34]:
arr2

array([[5, 5],
       [5, 4],
       [9, 2]], dtype=int32)

In [35]:
np.vstack([arr1,arr2])

array([[6, 1],
       [2, 5],
       [3, 6],
       [5, 5],
       [5, 4],
       [9, 2]], dtype=int32)

In [36]:
np.hstack([arr1,arr2])

array([[6, 1, 5, 5],
       [2, 5, 5, 4],
       [3, 6, 9, 2]], dtype=int32)

In [77]:
d=np.random.randint(1,10,size=(2,10,10))

In [78]:
np.split(d,2,axis=0)

[array([[[5, 6, 7, 4, 8, 2, 5, 4, 1, 8],
         [4, 9, 2, 6, 8, 4, 6, 4, 3, 7],
         [6, 9, 1, 2, 7, 9, 4, 9, 8, 4],
         [6, 6, 2, 3, 5, 8, 3, 6, 9, 3],
         [8, 1, 5, 3, 3, 5, 2, 4, 6, 2],
         [2, 2, 9, 1, 6, 5, 9, 3, 8, 3],
         [8, 8, 2, 8, 6, 8, 7, 2, 7, 8],
         [2, 9, 7, 3, 9, 5, 5, 2, 3, 8],
         [3, 9, 5, 5, 1, 6, 3, 4, 8, 9],
         [9, 2, 3, 9, 3, 7, 6, 5, 9, 7]]], dtype=int32),
 array([[[1, 3, 2, 4, 4, 3, 1, 8, 9, 7],
         [4, 8, 2, 2, 3, 6, 4, 6, 6, 6],
         [8, 7, 6, 8, 9, 4, 8, 9, 7, 4],
         [9, 9, 4, 4, 2, 2, 7, 1, 7, 5],
         [6, 4, 7, 1, 7, 7, 3, 8, 2, 8],
         [3, 6, 4, 3, 5, 1, 3, 3, 4, 8],
         [7, 8, 5, 8, 8, 6, 1, 9, 4, 1],
         [6, 6, 5, 2, 3, 6, 6, 1, 8, 3],
         [8, 8, 3, 4, 9, 8, 7, 8, 3, 5],
         [3, 9, 3, 8, 3, 1, 2, 7, 8, 9]]], dtype=int32)]

In [76]:
d

array([[[9, 3, 6, 6, 3, 2, 6, 3, 3, 1],
        [9, 5, 6, 4, 7, 1, 6, 3, 3, 3],
        [5, 4, 3, 8, 2, 1, 6, 2, 3, 3],
        [7, 8, 3, 6, 6, 9, 9, 2, 6, 6],
        [8, 8, 9, 2, 7, 7, 1, 4, 9, 6],
        [2, 8, 1, 2, 7, 8, 2, 4, 8, 8],
        [8, 9, 1, 3, 6, 2, 9, 7, 3, 3],
        [3, 4, 4, 3, 9, 9, 4, 4, 2, 1],
        [6, 9, 7, 1, 2, 8, 9, 3, 6, 9],
        [4, 5, 8, 4, 4, 6, 5, 3, 4, 8]],

       [[7, 1, 6, 2, 7, 3, 2, 1, 5, 1],
        [3, 5, 1, 2, 4, 4, 3, 1, 5, 4],
        [1, 9, 2, 6, 9, 6, 4, 3, 4, 5],
        [8, 6, 6, 6, 5, 6, 9, 3, 2, 5],
        [5, 2, 1, 3, 8, 9, 7, 7, 5, 3],
        [1, 7, 7, 5, 2, 6, 8, 3, 3, 4],
        [5, 8, 2, 7, 2, 2, 6, 5, 3, 2],
        [4, 6, 2, 7, 1, 3, 1, 7, 2, 5],
        [2, 8, 8, 9, 7, 6, 4, 6, 3, 4],
        [6, 1, 1, 9, 6, 9, 4, 9, 9, 6]]], dtype=int32)