In [39]:
#!python -m pip install --upgrade pip

In [43]:
#!pip install numpy

In [3]:
import numpy as np

In [4]:
np.__version__

'2.4.4'

# CREATING NUMPY ARRAY

In [5]:
list1=[1,2,3,3]


In [6]:

arr1=np.array(list1)

In [7]:
arr1

array([1, 2, 3, 3])

In [8]:
arr1.shape

(4,)

In [9]:
arr1.ndim

1

In [10]:
list2=[[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]
arr2=np.array(list2)

In [11]:
arr2

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [12]:
arr2.shape


(2, 2, 3)

In [13]:
arr2.ndim

3

In [14]:
np.zeros((2,2,3),dtype=int)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [15]:
np.ones((3,200,200),dtype=int)

array([[[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]],

       [[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]],

       [[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]]], shape=(3, 200, 200))

In [16]:
np.full((3,3),fill_value=2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [17]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [18]:
np.linspace(0,30,num=13)

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ,
       27.5, 30. ])

In [19]:
np.linspace((0,1,2),(10,20,30),num=5)

array([[ 0.  ,  1.  ,  2.  ],
       [ 2.5 ,  5.75,  9.  ],
       [ 5.  , 10.5 , 16.  ],
       [ 7.5 , 15.25, 23.  ],
       [10.  , 20.  , 30.  ]])

In [20]:
np.diag([2,3,4])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [21]:
np.identity(5
          )

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.random.randint(0,10,size=(2,3))

array([[6, 0, 9],
       [7, 9, 7]], dtype=int32)

In [23]:
np.random.randint(1,100,size=(4,3,2))

array([[[35, 57],
        [11, 37],
        [24, 88]],

       [[55, 17],
        [32, 51],
        [86, 32]],

       [[96, 78],
        [40, 49],
        [ 6,  6]],

       [[67, 89],
        [82,  8],
        [12, 44]]], dtype=int32)